project:
  type: website
  output-dir: docs

website:
  title: "DSCI 310: Historical Horse Population in Canada"
  navbar:
    left:
      - href: qmd_example.html
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



